name: Build and Test FastText

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # Use Ubuntu for Linux builds
    
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13]  # Use macOS 13 for macOS builds
        python: [3.8]
        architecture: [amd64, arm64]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
        
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel

      - name: Install build tools (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install build-essential python3-dev

      - name: Build the wheel
        run: |
          python setup.py bdist_wheel --plat-name=${{ runner.os }}_${{ matrix.architecture }} --python-tag=cp38

      - name: Test the wheel (optional)
        run: |
          # Install the wheel locally to test
          pip install dist/*.whl
          # You can add your test script here
          # python -m unittest discover

      - name: Upload artifact (wheel file)
        uses: actions/upload-artifact@v3  # Updated to version v3
        with:
          name: fasttext-wheel
          path: dist/*.whl
